[package]
name = "traders"
version = "0.1.0"
authors = ["Wouter Geraedts <git@woutergeraedts.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixed = { version = "1.1.0", features = ["az"] }
amethyst = { version = "0.15", features = ["vulkan", "no-slow-safety-checks"] }
